### ISSUE TITLE
about the example_bandgap.py

### ISSUE THREAD

**Issue by zc994646659** [albgar/aiida_siesta_plugin#127] opened 2024-07-10 07:54 UTC
Hello developer,

my aiida-core is 2.5.1.post0, aiida-siesta is 2.0.0

I've configured my computer and code, and I want to run runaiida example_bandgap.py siesta@shuguang. However, it seems to be reporting a pseudopotential issue:

ValueError: Error occurred validating port 'inputs.pseudos.Si': Invalid type <class 'aiida.orm.nodes.data.data.Data'> for dynamic port value: expected (<class 'aiida_pseudo.data.pseudo.psf.PsfData'>, <class 'aiida_pseudo.data.pseudo.psml.PsmlData'>)
I've already read the ../00_readme and configured:

aiida-pseudo list
Label                                Type string                Count
-----------------------------------  -------------------------  -------
psf_family                           pseudo.family              7
PseudoDojo/0.4/PBE/SR/standard/psml  pseudo.family.pseudo_dojo  72

So, how can I resolve this error?

**Comment by bosonie** [comment] 2024-07-11 06:20
Hello @zc994646659 .
Are we talking about the example in `aiida_siesta_plugin/aiida_siesta/examples/workflows` ???
I just tried myself `runaiida example_bandgap.py siesta_basic@localhost` on my computer and it works fine.
That particular example, does not use pseudo families for the pseudopotentials, but it retrieves the pseudo from the folder `aiida_siesta_plugin/aiida_siesta/examples/fixtures/sample_psf`, so there shouldn't be any difficulty there.

The only difference between your environment and mine is that I have `aiida-core==2.5.1`. You are using a development branch and it is impossible for me to have your exact version of aiida-core unless you send me info on the last commit of the aiida-core development. In any case, it is highly recommended to always use a stable version of aiida-core, unless you are testing new features. In conclusion, my suggestion is to `pip install aiida-core==2.5.1` and try to run the example again. In case this does not work, we will investigate further.

**Comment by zc994646659** [comment] 2024-07-22 01:42
Hello @bosonie ,

I have updated the following:

aiida-core 2.5.1
aiida-optimize 1.0.2
aiida-pseudo 1.5.0
aiida-siesta 2.0.0

However, it still shows a problem. When I run runaiida example_bandgap.py siesta@shuguang, it outputs:

/opt/conda/lib/python3.10/site-packages/aiida_siesta/calculations/siesta.py:136: AiidaDeprecationWarning: `KpointsData.get_attribute` is deprecated, use `KpointsData.base.attributes.get` instead. (this will be removed in v3)
  mesh = value.get_attribute("mesh", None)
Submitted workchain; ID=99
For information about this workchain type: verdi process show 99

When I run verdi process show 99, I get:

state        Excepted <ValueError: Error occurred validating port 'inputs.pseudos.Si': Invalid type <class 'aiida.orm.nodes.data.data.Data'> for dynamic port value: expected (<class 'aiida_pseudo.data.pseudo.psf.PsfData'>, <class 'aiida_pseudo.data.pseudo.psml.PsmlData'>)>

Is there something wrong with my configuration or something I overlooked? I just want to run a simple example, but I encountered this issue. I appreciate your quick feedback.

zhouchao

**Comment by bosonie** [comment] 2024-07-22 05:44
Hello, let's try a bit of debugging.
This is the code that generates the pseudos. Please open `verdi shell` and  run it MAKING SURE you are in the folder `aiida_siesta_plugin/aiida_siesta/examples/workflows`
```
import os.path as op
from aiida_pseudo.data.pseudo.psf import PsfData
pseudos_dict = {}
raw_pseudos = [("Si.psf", ['Si'])]
for fname, kinds in raw_pseudos:
    absname = op.realpath(op.join("../fixtures/sample_psf", fname))
    pseudo = PsfData.get_or_create(absname)
    if not pseudo.is_stored:
        print(f"\nCreated the pseudo for {kinds}")
    else:
        print(f"\nUsing the pseudo for {kinds} from DB: {pseudo.pk}")
    for j in kinds:
        pseudos_dict[j]=pseudo
```
What is the result? 
In the `pseudos_dict` there should be a pseudo for Si, that is of type `PsfData`. I suspect instead you might see a pseudo of type `Data`.
Once that is confirmed, can you please run the same code above, replacing the `raw_pseudos = [("Si.psf", ['Si'])]` with `raw_pseudos = [("H.psf", ['H'])]`?
What is the result now?
Thanks.

**Comment by zc994646659** [comment] 2024-07-22 08:13
Thanks @bosonie , It seems there are no issues. I followed your instructions and ran the code in verdi shell. The output was:

Using the pseudo for ['Si'] from DB: 4
After changing to H, it output:

Using the pseudo for ['H'] from DB: 6

Everything seems fine. Could it be a configuration issue with my machine?  
Thanks!

**Comment by zc994646659** [comment] 2024-07-23 06:16
@bosonie  My outputs appear normal, but the code is still not running as expected, which is quite frustrating. It is unclear where the problem lies. Could the issue be with the configuration submitted to the remote server?

**Comment by bosonie** [comment] 2024-07-24 05:40
Actually, this is not what I was expecting...
Can you please tell me the content of the `pseudos_dict` variable after running the code I wrote the other day..
I believe your pseudos are not set up correctly.... Your pseudos should be instances of `PsfData`.

**Comment by bosonie** [comment] 2024-07-25 05:55
@zc994646659 in any case, for sure you can solve the problem deleting all the psf pseudo you set up and running the code again. The code is created to automatically deal with the pseudos, there is no need to do anything in advance for the case you want to run. Other examples use pseudo families, but this is not what we are talking about here.

**Comment by zc994646659** [comment] 2024-09-18 07:56
@bosonie hello, there are fixtures folder in the parent directory, but I have a problem now regarding how to specify the memory for my job submission. When I submit the job, I get the following error: 
stderr=sbatch: error: Batch job submission failed: Job submission failed because too much memory was requested relative to the number of CPUs requested. The requested memory:CPU should be kept no more than DefMemPerCPU. 
I have set the job to use 16 cores, and on my server, the memory per core is 1850KB, but the default is 65533, so it results in an error. I tried setting max_memory_kb, but it didn't work. How can I adjust this?

**Comment by bosonie** [comment] 2024-09-26 16:23
Hello @zc994646659. The keyword to use is indeed `max_memory_kb`, be careful that it goes at the level of the `options`, not inside the `resources` dict. And also be aware that the units are kB.
Hope this helps

**Comment by zc994646659** [comment] 2024-09-29 02:33
Hello, @bosonie 

I can now successfully run the example_bandgap.py script, but I’m wondering if it’s possible not to specify the SBATCH --mem and --time options and instead let the system use its default values. Even if I don't set these parameters, they still appear automatically. Does this matter?

Also, it seems that the --time parameter is quite crucial, as it affects the *.fdf file settings. I noticed that if I don’t set --time, the default value is 00:22:40. For larger computation tasks, I might need to adjust this manually.

So my question is: Could I leave these two parameters unset in the slurm script to make the calculations more flexible?

Thanks!

**Comment by bosonie** [comment] 2024-09-29 17:25
Hello @zc994646659 
I believe that the default values are set up when one registers the computer (`verdi computer setup`).
Try to see what are your defaults using `verdi computer show <computer_id>`. Look at the  `Default memory (kB)/machine`.
In any case you can always set the time and memory at runtime, for instance you can look at line 103 of the `example_bandgap.py`. There I set the walltime for instance. You can change it as you prefer!

**Comment by bosonie** [comment] 2024-10-06 15:57
Closing since #128 says that the problem is solved and the example runs ok now.

**Closed as completed by bosonie** 2024-10-06 15:57 UTC
